- name: Install Kibana
  yum: 
    name: kibana
    state: installed

- name: Restart service kibana
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: kibana

- name: Start kibana
  service:
    name: kibana
    state: started
    enabled: yes
  
